# Generated by Django 5.0.4 on 2024-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('movetime', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
