# Generated by Django 5.0.4 on 2024-08-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viza_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pm', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
