# Generated by Django 5.0.4 on 2024-08-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='single_viza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='viza_items',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='viza'),
        ),
    ]
